version: "3.1"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: jhon123
    networks: 
      - api-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on: 
      - mongo
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: jhon123 
    networks: 
      - api-network  
      
  postgres:
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: faesa123  
    networks: 
      - api-network   

  adminer:
    image: adminer
    restart: always
    depends_on: 
     - postgres
    ports:
     - 8080:8080   
    networks: 
      - api-network  

  api:
      build: './backend/'
      image: jsnunes/projetoc2-api:v1
      restart: always
      ports: 
       - 3000:3000
      depends_on:
        - mongo
      networks: 
        - api-network

networks: 
  api-network:
    driver: bridge

